server:
  tomcat:
    uri-encoding: UTF-8
  port: 8088
  ssl:
    key-store: 1940818_www.jocelynh.top.pfx
    key-store-password: r1PVai3x
spring:
  datasource:
    url: jdbc:mysql://47.102.118.47:3306/hjh?useSSL=false
    username: root
    password: Sr841430159@
    driver-class-name: com.mysql.jdbc.Driver
    http:
      encoding:
        enabled: true
        force: true
        charset: utf-8
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  redis:
    port: 6379
    host: 47.102.118.47
